    const data2=["ipsum dolor sit amet consectetur adipisicing elit. Ratione voluptate magnam repellat saepe voluptas alias velit ab blanditiis, temporibus fugit accusamus, atque inventore perferendis. Dicta aut autem, labore quisquam magni accusamus molestiae odio doloribus quae modi maiores vero provident facere quia possimus voluptas similique reprehenderit nihil eum exercitationem aliquam! Officiis",
    "adjust pin touch lead pause may cover turkey bias stone pop joint sharp squad drift active input oven afraid oak guest senior aim moon freeze trick speed drop just tire shrug rank forty shed second treat paint to plain lots wonder change thirty winter regain uh evolve thick smile in cite heaven behind remove sound seldom unity minute fuel crowd horror ship cheese excuse widow bull others brave tender yours money beach ill scared thread help frozen rock should flame United shake place lately hardly hook school deploy stick green clue globe boom this title circle",
    "split risky rice raise total limb pill lonely entire system both till mill log plan want advise brutal health return easily poke unable tennis store peer nurse end freely then hello option corner editor toy spot eighth dish profit well stuff hall spread escape agree gaze mind rumor hurry live ritual shift than carrot know slam beef tray fan score change pair cabin order clerk broker world escape flight cause them once sample deer mine ski smooth pro openly pencil skin its seat black scan five like after flag policy occur plenty belong itself means own mate swear haul punch round catch rank gently letter tile cousin public sales age chief send feel little OK throw lawn domain neat tax rib chef bunch start eleven search e-mail inside very grant sink orange unlike",
    "These bear, mostly, as on one inclosing point of need. For after the rest is said-after the many time-honor'd and really true things for subordination, experience, rights of property, &c., have been listen'd to and acquiesced in-after the valuable and well-settled statement of our duties and relations in society is thoroughly conn'd over and exhausted-it remains to bring forward and modify everything else with the idea of that Something a man is, (last precious consolation of the drudging poor,) standing apart from all else, divine in his own right, and a woman in hers, sole",
    "the simple idea that the last, best dependence is to be upon humanity itself, and its own inherent, normal, fullgrown qualities, without any superstitious support whatever. This idea of perfect individualism it is indeed that deepest tinges and gives character to the idea of the aggregate. For it is mainly or altogether to serve independent separatism that we favor a strong generalization, consolidation. As it is to give the best vitality and freedom to the rights of the States, (every bit as important as the right of nationality, the union,) that we insist on the identity of the Union at all hazards",
    "The purpose of democracy-supplanting old belief in the necessary absoluteness of establish'd dynastic rulership, temporal, ecclesiastical, and scholastic, as furnishing the only security against chaos, crime, and ignorance-is, through many transmigrations, and amid endless ridicules, arguments, and ostensible failures, to illustrate, at all hazards, this doctrine or theory that man, properly train'd in sanest, highest freedom, may and must become a law, and series of laws, unto himself, surrounding and providing for, not only his own personal control, but all his relations to other individuals, and to the State;",
    "right song girl three family there let can form again so might same head almost came old almost move talk book between has my use just later look river last get us is will do still read sound fire did such at him took year way group close because earth point earth father help help get was family add these add mother thought eat take made away leave far they sea one number food will day head really upon world for her him food miss from need only children like",
    "To improve your typing speed, you need to practice typing frequently. That’s the only way to master the finger placement on each key and touch-typing pattern. Typing 10 minutes a day for 6 days will help you speed up your typing more than typing for an hour for only one day. That is because the more often you ask your fingers to remember where the letters are on your keyboard, the easier it will be to remember. After a month or two typing will become almost instinctive and you will be able to type without thinking about where the keys are",
    "THREE little Fairies sat in the fields eating their breakfast; each among the leaves of her favorite flower, Daisy, Primrose, and Violet, were happy as Elves need be. The morning wind gently rocked them to and fro, and the sun shone warmly down upon the dewy grass, where butterflies spread their gay wings, and bees with their deep voices sung among the flowers; while the little birds hopped merrily about to peep at them. On a silvery mushroom was spread the breakfast;"]

 
        let rand=Math.floor(Math.random()*9)
        console.log(rand)
        let data3=data2[rand]
        

let data=data3.split(' ')
export {data};

